# Generated by Django 5.1.7 on 2025-03-29 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energy_type', models.CharField(choices=[('fuel', 'Паливо'), ('gas', 'Газ'), ('electricity', 'Електроенергія')], max_length=20, unique=True, verbose_name='Тип енергоносія')),
                ('day_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Денний тариф')),
                ('night_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Нічний тариф')),
                ('unit', models.CharField(choices=[('liter', 'л'), ('cubic_meter', 'м³'), ('kwh', 'кВт·год')], max_length=20, verbose_name='Одиниця виміру')),
            ],
        ),
    ]
