# Generated by Django 5.1.6 on 2025-05-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0002_alter_tariff_energy_type_alter_tariff_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='energy_type',
            field=models.CharField(choices=[('fuel', 'Паливо'), ('gas', 'Газ'), ('electricity', 'Електроенергія'), ('air', 'Стисле повітря'), ('solution', 'Водно-мелясовий розчин')], max_length=20, unique=True, verbose_name='Тип енергоносія'),
        ),
    ]
