# Generated by Django 5.1.6 on 2025-04-30 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name="Ім'я лаборанта")),
            ],
            options={
                'verbose_name': 'Лаборант',
                'verbose_name_plural': 'Лаборанти',
            },
        ),
    ]
