# Generated by Django 5.0.4 on 2025-04-29 15:30

from django.db import migrations

# Функція для додавання даних
def add_lab_workers(apps, schema_editor):
    LabWorker = apps.get_model('users', 'LabWorker')
    workers = [
        {'id': 1, 'name': 'Лаборант 1'},
        {'id': 2, 'name': 'Лаборант 2'},
        {'id': 3, 'name': 'Лаборант 3'},
        {'id': 4, 'name': 'Лаборант 4'},
        {'id': 5, 'name': 'Лаборант 5'},
    ]
    for worker_data in workers:
        # Використовуємо get_or_create, щоб уникнути помилок при повторному запуску
        LabWorker.objects.get_or_create(id=worker_data['id'], defaults={'name': worker_data['name']})

# Функція для видалення даних (при відкаті міграції)
def remove_lab_workers(apps, schema_editor):
    LabWorker = apps.get_model('users', 'LabWorker')
    LabWorker.objects.filter(id__in=[1, 2, 3, 4, 5]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_labworker'), # Залежить від попередньої міграції
    ]

    operations = [
        migrations.RunPython(add_lab_workers, remove_lab_workers),
    ]
