# Generated by Django 5.1.7 on 2025-03-28 14:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='task',
            name='brand',
            field=models.CharField(choices=[('N772', 'Марка N772'), ('N326', 'Марка N326'), ('N220', 'Марка N220')], default='N772', max_length=20, verbose_name='Марка продукту'),
        ),
        migrations.AddField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Кінцевий термін'),
        ),
        migrations.AddField(
            model_name='task',
            name='line',
            field=models.CharField(choices=[('1', 'Лінія 1'), ('2', 'Лінія 2')], default='1', max_length=10, verbose_name='Лінія сушіння'),
        ),
        migrations.AddField(
            model_name='task',
            name='quantity',
            field=models.PositiveIntegerField(default=100, verbose_name='Кількість продукції (кг)'),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('new', 'Нове'), ('in_progress', 'В процесі'), ('done', 'Виконано')], default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
