# Generated by Django 5.1.7 on 2025-04-29 10:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_task_assigned_to_task_brand_task_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='moisture',
            field=models.FloatField(default=0.3, help_text='Діапазон: 0.2 - 0.9', validators=[django.core.validators.MinValueValidator(0.2), django.core.validators.MaxValueValidator(0.9)], verbose_name='Потрібна вологість (%)'),
        ),
        migrations.AddField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('new', 'Нове'), ('in_progress', 'В процесі'), ('done', 'Виконано'), ('done_late', 'Виконано з запізненням'), ('failed', 'Не виконано')], default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
