# Generated by Django 5.1.6 on 2025-04-30 08:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_moisture_task_updated_at_alter_task_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('N772', 'Марка N772'), ('N326', 'Марка N326'), ('N220', 'Марка N220')], max_length=20, unique=True, verbose_name='Марка продукту')),
                ('min_moisture', models.FloatField(default=0.2, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Мін. Вологість (%)')),
                ('max_moisture', models.FloatField(default=0.9, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Макс. Вологість (%)')),
                ('max_ash', models.FloatField(default=0.45, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Макс. Зольність (%)')),
                ('min_hardness', models.FloatField(default=10.0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Мін. Твердість (г)')),
                ('max_hardness', models.FloatField(default=50.0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Макс. Твердість (г)')),
            ],
            options={
                'verbose_name': 'Показник якості',
                'verbose_name_plural': 'Показники якості',
            },
        ),
        migrations.CreateModel(
            name='LabMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_time', models.DateTimeField(auto_now_add=True, verbose_name='Час вимірювання')),
                ('measured_moisture', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Виміряна вологість (%)')),
                ('measured_ash', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Виміряна зольність (%)')),
                ('measured_hardness', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Виміряна твердість (г)')),
                ('measured_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_measurements_taken', to=settings.AUTH_USER_MODEL, verbose_name='Виміряв(ла)')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_measurements', to='tasks.task', verbose_name='Виробниче завдання')),
            ],
            options={
                'verbose_name': 'Лабораторне вимірювання',
                'verbose_name_plural': 'Лабораторні вимірювання',
                'ordering': ['-measurement_time'],
            },
        ),
    ]
