# Generated by Django 5.1.6 on 2025-04-30 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_qualityindicator_labmeasurement'),
        ('users', '0003_populate_labworkers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labmeasurement',
            name='measured_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_measurements_taken', to='users.labworker', verbose_name='Виміряв(ла)'),
        ),
    ]
