# Generated by Django 5.1.6 on 2025-05-01 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_labmeasurement_measured_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskProcessParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='Час останнього оновлення')),
                ('initial_moisture', models.FloatField(blank=True, null=True, verbose_name='Поч. вологість (%)')),
                ('initial_temp', models.FloatField(blank=True, null=True, verbose_name='Поч. температура (°C)')),
                ('axial_burner_temp', models.FloatField(blank=True, null=True, verbose_name='Темп. осьового пальника (°C)')),
                ('zone1_drum_temp', models.FloatField(blank=True, null=True, verbose_name='Зона 1: Темп. барабану (°C)')),
                ('zone1_burner_temp', models.FloatField(blank=True, null=True, verbose_name='Зона 1: Темп. пальника (°C)')),
                ('zone1_1_carbon_temp', models.FloatField(blank=True, null=True, verbose_name='Зона 1.1: Темп. вуглецю (°C)')),
                ('zone1_1_carbon_moisture', models.FloatField(blank=True, null=True, verbose_name='Зона 1.1: Вологість вуглецю (%)')),
                ('zone1_2_carbon_temp', models.FloatField(blank=True, null=True, verbose_name='Зона 1.2: Темп. вуглецю (°C)')),
                ('zone1_2_carbon_moisture', models.FloatField(blank=True, null=True, verbose_name='Зона 1.2: Вологість вуглецю (%)')),
                ('zone2_drum_temp', models.FloatField(blank=True, null=True, verbose_name='Зона 2: Темп. барабану (°C)')),
                ('zone2_burner_temp', models.FloatField(blank=True, null=True, verbose_name='Зона 2: Темп. пальника (°C)')),
                ('zone2_1_carbon_temp', models.FloatField(blank=True, null=True, verbose_name='Зона 2.1: Темп. вуглецю (°C)')),
                ('zone2_1_carbon_moisture', models.FloatField(blank=True, null=True, verbose_name='Зона 2.1: Вологість вуглецю (%)')),
                ('zone2_2_carbon_temp', models.FloatField(blank=True, null=True, verbose_name='Зона 2.2: Темп. вуглецю (°C)')),
                ('zone2_2_carbon_moisture', models.FloatField(blank=True, null=True, verbose_name='Зона 2.2: Вологість вуглецю (%)')),
                ('zone3_drum_temp', models.FloatField(blank=True, null=True, verbose_name='Зона 3: Темп. барабану (°C)')),
                ('zone3_burner_temp', models.FloatField(blank=True, null=True, verbose_name='Зона 3: Темп. пальника (°C)')),
                ('zone3_1_carbon_temp', models.FloatField(blank=True, null=True, verbose_name='Зона 3.1: Темп. вуглецю (°C)')),
                ('zone3_1_carbon_moisture', models.FloatField(blank=True, null=True, verbose_name='Зона 3.1: Вологість вуглецю (%)')),
                ('zone3_2_carbon_temp', models.FloatField(blank=True, null=True, verbose_name='Зона 3.2: Темп. вуглецю (°C)')),
                ('zone3_2_carbon_moisture', models.FloatField(blank=True, null=True, verbose_name='Зона 3.2: Вологість вуглецю (%)')),
                ('final_temp', models.FloatField(blank=True, null=True, verbose_name='Кінц. температура (°C)')),
                ('final_moisture', models.FloatField(blank=True, null=True, verbose_name='Кінц. вологість (%)')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_parameters_history', to='tasks.task', verbose_name='Виробниче завдання')),
            ],
            options={
                'verbose_name': 'Параметр процесу завдання',
                'verbose_name_plural': 'Параметри процесу завдань',
                'ordering': ['-timestamp'],
            },
        ),
    ]
