# Generated by Django 5.1.6 on 2025-05-02 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_taskprocessparameters'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID Типу енергії')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Назва типу енергії')),
            ],
            options={
                'verbose_name': 'Тип енергії',
                'verbose_name_plural': 'Типи енергії',
            },
        ),
        migrations.CreateModel(
            name='EnergyFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(blank=True, null=True, verbose_name='Витрата енергії (од.)')),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='Час запису')),
                ('process_params', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='energy_flows', to='tasks.taskprocessparameters', verbose_name='Параметри процесу (запис)')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='energy_flows', to='tasks.task', verbose_name='Виробниче завдання')),
                ('energy_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.energytype', verbose_name='Тип енергії')),
            ],
            options={
                'verbose_name': 'Потік енергії',
                'verbose_name_plural': 'Потоки енергії',
                'ordering': ['-timestamp', 'energy_type'],
            },
        ),
        migrations.CreateModel(
            name='RawMaterialFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=20, null=True, verbose_name='Марка продукту (на момент запису)')),
                ('carbon_flow_rate', models.FloatField(blank=True, null=True, verbose_name='Витрата вуглецю (кг/с)')),
                ('solution_flow_rate', models.FloatField(blank=True, null=True, verbose_name='Витрата розчину (кг/с)')),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='Час запису')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_material_flows', to='tasks.task', verbose_name='Виробниче завдання')),
            ],
            options={
                'verbose_name': 'Потік сировини',
                'verbose_name_plural': 'Потоки сировини',
                'ordering': ['-timestamp'],
            },
        ),
    ]
