# Generated by Django 5.1.6 on 2025-05-02 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_energytype_energyflow_rawmaterialflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Час початку виконання'),
        ),
    ]
